stages:
  get_data:
    cmd: python src/download_data.py
    deps:
    - src/download_data.py
    outs:
    - data/raw/iris.csv
  process_data:
    cmd: python src/process_data.py
    deps:
    - data/raw/iris.csv
    - src/process_data.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
